let stores = [{
    store_latitude: "53.2869", store_longitude: "-6.375032",
location: "Tallaght",
store_address: "Bellgard square Tallaght, D24 Co.",
store_Co : " Dublin",
store_description: "",
store_direction: "294.33",
store_facilities: ["delivery", "papajohns", "wifi"],
store_front_image: false,
store_latitude: "53.2869",
store_link: "https://papajohns.ie/store/tallaght/",
store_longitude: "-6.375032",
store_opening_hours: "12:00",
store_telephone: "01 4057777",
store_tilt: "3",
store_zoom_level: "50"}
,{
location: "Papa Johns Larkin Cross",
store_address: "Larkin's Cross, Wexford,Co.",
store_Co : " Wexford",
store_description: "",
store_direction: "290.26",
store_facilities: ["drivethru", "papajohns", "wifi", "parking"],
store_latitude: "52.339359",
store_link: "https://papajohns.ie/store/supermacs-papa-johns-larkins-cross/",
store_longitude: "-6.564814",
store_opening_hours: "10:00",
store_telephone: "053 9120010",
store_tilt: "3",
store_zoom_level: "85.91",
},{
location: "Papa John Oughterard",
store_address: "Main Street,Oughterard,Co. ",
store_Co : " Galway",

store_facilities: ["papajohns", "wifi", "parking"],
store_latitude: "53.428231",
store_link: "https://papajohns.ie/store/papa-johns-oughterard/",
store_longitude: "-9.317935",
store_opening_hours: "12:00",
store_telephone: "091 866010"},
{
location: "Kinnegad Plaza",
store_address: "Kinnegad Co. ",
store_Co : " Westmeath",
store_direction: "290.26",
store_facilities: ["drivethru", "papajohns", "wifi", "parking", "babychanging"],
store_latitude: "53.452375",
store_link: "https://papajohns.ie/store/kinnegad-plaza/",
store_longitude: "-7.106149",
store_opening_hours: "11:00",
store_telephone: "(044) 937 9020",
}, 
{
location: "Naas",
store_address: "Monread Fare, Monread Road, Monread North, Naas, Co. ",
store_Co : " Kildare",
store_direction: "290.26",
store_facilities: ["delivery", "papajohns", "wifi"],
store_latitude: "53.24135100",
store_link: "https://papajohns.ie/store/naas/",
store_longitude: "-6.65701800",
store_opening_hours: "11:00",
store_telephone: "045 831155",
store_tilt: "3",
store_zoom_level: "85.91",
 
},
{
    location: "Birr",
    store_address: "Railway Rd, Seefin, Birr Co. ",
    store_Co: " Offaly",
    store_direction: "290.26",
    store_facilities: ["papajohns", "wifi", "parking", "babychanging"],
    store_latitude: "53.092757",
    store_link: "https://papajohns.ie/store/birr/",
    store_longitude: "-7.907859",
    store_opening_hours: "11:00",
    store_telephone: "(057) 912 2510",
    
    },
    {
    location: "Tivoli",
    store_address: "Lota More, Glanmire Rd Co. ",
    store_Co: " Cork",
    store_direction: "290.26",
    store_facilities: ["drivethru", "papajohns", "quiznos", "timhorton", "wifi", "parking", "babychanging"],
    store_latitude: "51.903147",
    store_link: "https://papajohns.ie/store/tivoli/",
    store_longitude: "-8.428005",
    store_opening_hours: "11:00",
    store_telephone: "(021) 450 2998",
    },
    {
    location: "Headford",
    store_address: "Galway Rd. Headford, Co. ",
    store_Co: " Galway",
    store_direction: "290.26",
    store_facilities: ["papajohns", "wifi", "parking", "babychanging"],
    store_latitude: "53.468073",
    store_link: "https://papajohns.ie/store/headford/",
    store_longitude: "-9.105991",
    store_opening_hours: "09:00",
    store_telephone: "093 36443",
    },
    {
    location: "Donegal Service Station",
    store_address: "Donegal Service Station,Drumlonagher, Donegal Town",
    store_Co: " Donegal",
    store_direction: "290.26",
    store_facilities: ["drivethru", "papajohns", "quiznos", "timhorton", "wifi", "parking", "babychanging"],
    store_front_image: false,
    store_latitude: "54.659013",
    store_link: "https://papajohns.ie/store/donegal-service-station/",
    store_longitude: "-8.089249",
    store_opening_hours: "08:00",
    store_telephone: "074 9740484",
    },
    {
    location: "Bandon Road",
    store_address: "Supermac's ,Garranedarragh,Bandon Road,Bishopstown",
    store_Co: " Cork",
    store_direction: "290.26",
    store_facilities: ["papajohns", "wifi", "parking", "babychanging"],
    store_latitude: "51.871948",
    store_link: "https://papajohns.ie/store/bandon-road/",
    store_longitude: "-8.522224",
    store_opening_hours: "12:00",
    store_telephone: "021 7355688",
    },
    {
    location: "North Ring Road, Ballyvolane",
    store_address: "North Ring Road, Ballyvolane ",
    store_Co: " Cork",
    store_direction: "290.26",
    store_facilities: ["drivethru", "papajohns", "timhorton", "wifi", "parking", "babychanging"],
    store_latitude: "51.914763",
    store_link: "https://papajohns.ie/store/ballyvolane/",
    store_longitude: "-8.447753",
    store_opening_hours: "11:00",
    store_telephone: "021 4551536",
    },
    {
    location: "Balbriggan, Dublin",
    store_address: "Supermac's,Dublin St.,Balbriggan Co. ",
    store_Co: " Dublin",
    store_direction: "290.26",
    store_facilities: ["drivethru", "papajohns", "quiznos", "timhorton", "wifi", "parking", "babychanging"],
    store_latitude: "53.605348",
    store_link: "https://papajohns.ie/store/balbriggan-dublin/",
    store_longitude: "-6.184380",
    store_opening_hours: "9:00",
    store_telephone: "(01) 883 4013",
    },
    {
    location: "Ballysimon Rd, Limerick",
    store_address: "Papa John’s & Supermac’s Drive Thru,Ballysimon Road,Ballysimon",
    store_Co: " Limerick",
    store_direction: "290.26",
    store_facilities: ["drivethru", "papajohns", "quiznos", "timhorton", "wifi", "parking", "babychanging"],
    store_latitude: "52.652729",
    store_link: "https://papajohns.ie/store/ballysimon-rd-limerick/",
    store_longitude: "-8.594711",
    store_opening_hours: "11:00",
    store_telephone: "061 294414",
    },
    {
    location: "Tullow",
    store_address: "Flynn's Top Oil,Dublin Road,Tullow,Co. ",
    store_Co: " Carlow",
    store_direction: "290.26",
    store_facilities: ["papajohns", "wifi", "parking", "babychanging"],
    store_latitude: "52.804332",
    store_link: "https://papajohns.ie/store/tullow-2/",
    store_longitude: "-6.733015",
    store_opening_hours: "12:00",
    store_telephone: "059 9152739",
    },
    {
    location: "Charlestown Service Station",
    store_address: "Ballyhaunis Road,Charlestown,Co ",
    store_Co: " Mayo",
    store_direction: "290.26",
    store_facilities: ["papajohns", "quiznos", "wifi", "parking"],
    store_latitude: "53.960172",
    store_link: "https://papajohns.ie/store/charlestown-service-station/",
    store_longitude: "-8.793248",
    store_opening_hours: "07:00",
    store_telephone: "(094) 905 3484",
    },
    {
    location: "Trim",
    store_address: "Trim Retail Park,Navan Road Co. ",
    store_Co: " Meath",
    store_direction: "290.26",
    store_facilities: ["drivethru", "papajohns", "wifi", "parking", "babychanging"],
    store_latitude: "53.562618",
    store_link: "https://papajohns.ie/store/trim-2/",
    store_longitude: "-6.765679",
    store_opening_hours: "10:00",
    store_telephone: "046 9420007",
    },
    {
    location: "Barack Obama Plaza Moneygall",
    store_address: "The Barack Obama Plaza Junction 23, M7 Moneygall,Co. ",
    store_Co: " Tipperary",
    store_direction: "290.26",
    store_facilities: ["drivethru", "papajohns", "quiznos", "timhorton", "wifi", "parking", "babychanging"],
    store_latitude: "52.8860606",
    store_link: "https://papajohns.ie/store/barack-obama-plaza-moneygall/",
    store_longitude: "-7.9443857",
    store_opening_hours: "11",
    store_telephone: "0505 45808",
    },
    {
    location: "The Galway Plaza",
    store_address: "The Galway Plaza,Carrowkeel,Kiltullagh,Athenry",
    store_Co: " Galway",
    store_direction: "290.26",
    store_facilities: ["papajohns", "quiznos", "wifi", "parking", "babychanging"],
    store_latitude: "53.264392",
    store_link: "https://papajohns.ie/store/galway-plaza/",
    store_longitude: "-8.606688",
    store_opening_hours: "11:00",
    store_telephone: "091 848060",
    },
    {
    location: "Tipperary Town Plaza",
    store_address: "Tipperary Town Plaza,Limerick Road",
    store_Co: " Tipperary",
    store_direction: "291.42",
    store_facilities: ["drivethru", "delivery", "papajohns", "wifi", "parking"],
    store_latitude: "52.4794861",
    store_link: "https://papajohns.ie/store/tipperary-town-plaza/",
    store_longitude: "-8.1764386",
    store_opening_hours: "11:00",
    store_telephone: "062 80260",
    },
    {
    location: "Drogheda",
    store_address: "M1 Retail Park Mell,Drogheda,Co. ",
    store_Co: " Louth",
    store_direction: "135.36",
    store_facilities: ["drivethru", "delivery", "papajohns", "wifi", "parking"],
    store_latitude: "53.727997",
    store_link: "https://papajohns.ie/store/drogheda/",
    store_longitude: "-6.390903",
    store_opening_hours: "11:00",
    store_telephone: "041 9834100",
    },
    {
    location: "Clonshaugh",
    store_address: "Clonshaugh Road, Clonshaugh, Cloghran, Swords,Co.",
    store_Co: " Dublin",
    store_direction: "14.04",
    store_facilities: ["wifi", "parking", "babychanging"],
    store_latitude: "53.411",
    store_link: "https://papajohns.ie/store/clonshaugh/",
    store_longitude: "-6.2166",
    store_opening_hours: "11:00",
    store_telephone: "01 8488878",
    },
    {
    location: "Ballacolla",
    store_address: "Manor Stone Service Station,Tintore, Ballacolla,Co. ",
    store_Co: " Laois",
    store_direction: "290.26",
    store_facilities: ["papajohns", "wifi", "parking", "babychanging"],
    store_latitude: "52.8669704",
    store_link: "https://papajohns.ie/store/ballacolla/",
    store_longitude: "-7.481914",
    store_opening_hours: "11:00",
    store_telephone: "057 8734044",
    },
    {
    location: "Papa Johns Westport",
    store_address: "Texaco Service Station,Sheean,Westport,Co.",
    store_Co: " Mayo",
    store_direction: "216.54",
    store_facilities: ["papajohns", "parking"],
    store_latitude: "53.803363",
    store_link: "https://papajohns.ie/store/papa-johns-westport/",
    store_longitude: "-9.473064",
    store_opening_hours: "11:00",
    store_telephone: "098 27997",
    },
    {
    location: "Sligo",
    store_address: "Bundoran Road,Co. ",
    store_Co: " Sligo",
    store_direction: "289.19",
    store_facilities: ["drivethru", "papajohns", "wifi", "parking", "babychanging"],
    store_latitude: "54.2830039",
    store_link: "https://papajohns.ie/store/bundoran/",
    store_longitude: "-8.4725732",
    store_opening_hours: "10:00",
    store_telephone: "071- 9147555",
    },
    {
    location: "Main Street Ballinasloe",
    store_address: "Main Street,Ballinasloe,Co. ",
    store_Co: " Galway",
    store_direction: "160.54",
    store_facilities: ["delivery", "papajohns", "wifi"],
    store_latitude: "53.330825",
    store_link: "https://papajohns.ie/store/main-street/",
    store_longitude: "-8.220067",
    store_opening_hours: "11:00",
    store_telephone: "090-9643151",
    },
    {
    location: "Templebar",
    store_address: "26 Temple Bar,East Essex Street,Dublin 2,Co. ",
    store_Co: " Dublin",
    store_direction: "173.45",
    store_facilities: ["papajohns", "wifi"],
    store_latitude: "53.345461",
    store_link: "https://papajohns.ie/store/templebar/",
    store_longitude: "-6.264637",
    store_opening_hours: "12:00",
    store_telephone: "01 6706774",
    },
    {
    location: "Charleville",
    store_address: "Main Street,Charleville,Co. ",
    store_Co: " Cork",
    store_direction: "69.69",
    store_facilities: ["wifi"],
    store_latitude: "52.354297",
    store_link: "https://papajohns.ie/store/charleville-2/",
    store_longitude: "-8.682535",
    store_opening_hours: "08:00",
    store_telephone: "063 32000",
    },
    {
    location: "Singland",
    store_address: "Dublin Road,Castletroy ",
    store_Co: " Limerick ",
    store_direction: "1.37",
    store_facilities: ["delivery", "papajohns", "wifi", "parking", "babychanging"],
    store_latitude: "52.664922",
    store_link: "https://papajohns.ie/store/singland/",
    store_longitude: "-8.582388",
    store_opening_hours: "10:00",
    store_telephone: "061 216161",
    },
    {
    location: "Ballindine",
    store_address: "Texaco Service Station,Ballindine,Co. ",
    store_Co: " Mayo",
    store_direction: "201.86",
    store_facilities: ["drivethru", "papajohns", "wifi", "parking"],
    store_latitude: "53.668296",
    store_link: "https://papajohns.ie/store/ballindine/",
    store_longitude: "-8.955606",
    store_opening_hours: "11:00",
    store_telephone: "094 9364600",
    },
    {
    location: "Ballina",
    store_address: "Pearse street,Ballina,Co. ",
    store_Co: " Mayo",
    store_direction: "301.62",
    store_facilities: ["delivery", "papajohns", "wifi"],
    store_latitude: "54.11365",
    store_link: "https://papajohns.ie/store/ballina/",
    store_longitude: "-9.154842",
    store_opening_hours: "11:00",
    store_telephone: "096 72241",
    },
    {
    location: "Oranmore",
    store_address: "Oranmore,Co. ",
    store_Co: " Galway",
    store_direction: "101.27",
    store_facilities: ["delivery", "papajohns", "wifi", "parking"],
    store_latitude: "53.2678983",
    store_link: "https://papajohns.ie/store/oranmore/",
    store_longitude: "-8.9297832",
    store_opening_hours: "12:00",
    store_telephone: "091 790080",
    }
]